#!/usr/bin/env python3
"""
apply_profile.py — install the design system in a consuming project.

Copies the foundation (tokens, core, themes, components) and the requested
profile's overlay on top, then writes the entry `index.css` with the layer order
and imports that **resolve from the project** (a profile's own `index.css`
imports a skill-relative path that breaks once copied).
"""

from __future__ import annotations

import argparse
import json
import shutil
import sys
from pathlib import Path

if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass

EXIT_OK, EXIT_ERROR, EXIT_USAGE = 0, 1, 64

#: Layers are declared before any `@import` (only `@charset` or an empty `@layer` may precede one).
INDEX_TEMPLATE = """/* Generated by `scripts/apply_profile.py` — profile `{profile}`.
 * Everything from the system lives in a `@layer`: unlayered project CSS always
 * wins, so existing styles keep control while the migration runs.
 */
@layer ui.reset, ui.tokens, ui.core, ui.theme;
{fonts}
/* Foundation: invariant primitives, `data-ui` slot mechanics, and the theme. */
@import "./tokens.css";
@import "./core.css";
{themes}{overlay}"""

FONTS_NOTICE = """
/* The profile's fonts are the project's binaries, not this skill's. Install them
 * and uncomment these lines — no CDN: a remote font fails the audit under
 * `offline: true`, and a font that does not load silently becomes another one.
 *
 *   npm i {packages}
 *
{imports}
 */
"""


def _copy(source: Path, target: Path, dry: bool) -> None:
    if dry:
        print(f"[dry] {source.name} -> {target}")
        return
    target.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, target)


def _ui_folder(project: Path, explicit: str | None) -> Path:
    if explicit:
        return project / explicit
    for candidate in ("src/ui", "packages/ui/src", "packages/ui-react/src"):
        if (project / candidate).exists():
            return project / candidate
    return project / "src/ui"


def _profile_fonts(config: dict) -> tuple[list[str], list[str]]:
    """npm packages and `@import`s of the fonts the profile declares."""
    fonts = (config.get("styling") or {}).get("fonts") or {}
    packages, imports = [], []
    for key in ("sans", "mono", "serif"):
        name = fonts.get(key)
        if not name:
            continue
        # "Instrument Sans Variable" -> @fontsource-variable/instrument-sans
        base = name.replace(" Variable", "").strip().lower().replace(" ", "-")
        package = f"@fontsource-variable/{base}" if "Variable" in name else f"@fontsource/{base}"
        packages.append(package)
        imports.append(f' * @import "{package}";')
    return packages, imports


def apply(skill: Path, project: Path, profile: str | None, dry: bool, ui_dir: str | None,
          with_tailwind: bool, with_react: bool = False) -> int:
    if profile:
        profile_dir = skill / "profiles" / profile
        if not profile_dir.is_dir():
            print(f"Error: profile '{profile}' does not exist in {profile_dir}", file=sys.stderr)
            profiles = skill / "profiles"
            available = sorted(p.name for p in profiles.iterdir() if p.is_dir()) if profiles.is_dir() else []
            print(f"Available profiles: {', '.join(available) or '(none — use the base profile with no argument)'}",
                  file=sys.stderr)
            return EXIT_ERROR
    else:
        profile = "base"
        profile_dir = skill / "assets"

    ui = _ui_folder(project, ui_dir)
    css = ui / "css"
    rel_ui = ui.relative_to(project).as_posix()
    print(f"==> profile '{profile}' in {project}  (UI in {rel_ui}/)")

    profile_config = profile_dir / "ui.config.json"
    config = json.loads(profile_config.read_text(encoding="utf-8")) if profile_config.is_file() else {}

    # -- 1. Foundation: tokens, core and components -------------------------
    for name in ("tokens.css", "core.css"):
        _copy(skill / "assets" / "css" / name, css / name, dry)

    if with_tailwind:
        _copy(skill / "assets" / "css" / "tailwind-bridge.css", css / "tailwind-bridge.css", dry)

    # Components are a React pack, copied only when the profile (or --with-react) asks.
    if bool(config.get("react")) or with_react:
        components = sorted((skill / "packs" / "react-components").glob("*.ts*"))
        for f in components:
            _copy(f, ui / "components" / f.name, dry)
        print(f"  · {len(components)} React components (packs/react-components)")
    else:
        print("  · React components not copied (no 'react' in the profile; use --with-react)")

    # -- 2. Only the themes the profile declares ----------------------------
    themes = config.get("themes") or (config.get("styling") or {}).get("themes") or ["neutral"]
    for theme in themes:
        source = skill / "assets" / "css" / "themes" / f"{theme}.css"
        if source.is_file():
            _copy(source, css / "themes" / f"{theme}.css", dry)
    print(f"  · themes: {', '.join(themes)}")

    # -- 3. The profile overlay, in `css/profile/` so a foundation update never overwrites it
    overlay = []
    profile_css = profile_dir / "assets" / "css"

    def _order(name: str) -> int:
        return {"tokens.css": 0, "core.css": 1}.get(name, 2)  # define, then draw, theme last

    files = sorted(profile_css.glob("*.css")) + sorted(profile_css.glob("themes/*.css"))
    for source in sorted(files, key=lambda f: (_order(f.name), f.name)):
        if source.name.startswith("index"):
            continue  # the entry is generated, not copied
        target_name = source.name if source.parent.name != "themes" else f"theme-{source.name}"
        _copy(source, css / "profile" / target_name, dry)
        overlay.append(target_name)

    # -- 4. The entry, with imports that resolve from here ------------------
    packages, imports = _profile_fonts(config)
    fonts_block = FONTS_NOTICE.format(packages=" ".join(packages), imports="\n".join(imports)) if packages else ""
    themes_block = "".join(f'@import "./themes/{t}.css";\n' for t in themes
                           if (skill / "assets" / "css" / "themes" / f"{t}.css").is_file())
    overlay_block = ""
    if overlay:
        overlay_block = ("\n/* The profile overlay on top of the foundation. */\n"
                         + "".join(f'@import "./profile/{n}";\n' for n in overlay))

    index = INDEX_TEMPLATE.format(profile=profile, fonts=fonts_block, themes=themes_block, overlay=overlay_block)
    if dry:
        print(f"[dry] would write {css / 'index.css'}")
    else:
        css.mkdir(parents=True, exist_ok=True)
        (css / "index.css").write_text(index, encoding="utf-8")
    print(f"  · {rel_ui}/css/index.css")

    # -- 5. ui.config.json, pointing at where the UI actually landed ---------
    if config:
        config["uiSource"] = rel_ui
        config["tokensSource"] = f"{rel_ui}/css"
        config["cssSource"] = f"{rel_ui}/css"
        base = config.get("basePrimitive")
        if isinstance(base, dict):
            base["allowedInside"] = [rel_ui]
        if dry:
            print(f"[dry] would write {project / 'ui.config.json'}")
        else:
            (project / "ui.config.json").write_text(
                json.dumps(config, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
        print("  · ui.config.json")

    print("\nNext:")
    print(f"  npm i @base-ui/react {' '.join(packages)}".rstrip())
    print(f"  import `{rel_ui}/css/index.css` at app start")
    print(f"  python {skill / 'scripts' / 'audit_ui.py'} {project} --profile {profile} --strict")
    return EXIT_OK


class _Parser(argparse.ArgumentParser):
    def error(self, message: str):
        self.print_usage(sys.stderr)
        print(f"usage error: {message}", file=sys.stderr)
        raise SystemExit(EXIT_USAGE)


def main() -> int:
    ap = _Parser(description="Install the design system and a profile in a project.")
    ap.add_argument("profile", nargs="?", default=None,
                    help="Profile in profiles/<name>/ (optional; without it, assets/ui.config.json)")
    ap.add_argument("--target", default=".", help="Target project (default: .)")
    ap.add_argument("--ui-dir", default=None,
                    help="Where to put the UI, relative to the target (default: src/ui, or what exists)")
    ap.add_argument("--tailwind", action="store_true", help="Include the Tailwind v4 bridge. Without it, CSS only.")
    ap.add_argument("--with-react", action="store_true",
                    help="Also copy the React components pack (packs/react-components).")
    ap.add_argument("--dry-run", action="store_true", help="Simulate, write nothing")
    args = ap.parse_args()

    skill = Path(__file__).resolve().parents[1]
    project = Path(args.target).resolve()
    if not project.is_dir():
        print(f"Error: target '{project}' is not a directory", file=sys.stderr)
        return EXIT_ERROR
    return apply(skill, project, args.profile, args.dry_run, args.ui_dir, args.tailwind, args.with_react)


if __name__ == "__main__":
    sys.exit(main())
